### ISSUE TITLE
test failures after parent is upgraded to spring-cloud-build 1.2.1.RELEASE

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud-stream-app-starters/hdfs#2]
Stacktrace:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkConfigurationTests
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.977 sec <<< FAILURE!
testWritingSomething(org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkConfigurationTests)  Time elapsed: 0.288 sec  <<< ERROR!
java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@1eeb5818 testClass = HdfsSinkConfigurationTests, locations = '{}', classes = '{class org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkConfigurationTests$HdfsSinkApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{server.port:0, spring.hadoop.fsUri=file:///, hdfs.directory=${java.io.tmpdir}/hdfs-sink, hdfs.closeTimeout=100, org.springframework.boot.test.WebIntegrationTest=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@149e0f5d, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@17046283], resourceBasePath = '', contextLoader = 'org.springframework.boot.test.SpringApplicationContextLoader', parent = [null]]] is not active. Ensure that the context has not been closed programmatically.
	at org.springframework.util.Assert.state(Assert.java:392)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:87)
	at org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener.afterTestMethod(MockRestServiceServerResetTestExecutionListener.java:35)
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:319)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkIntegrationTests
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.682 sec <<< FAILURE!
testWritingSomething(org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkIntegrationTests)  Time elapsed: 0.097 sec  <<< ERROR!
java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@4348fa35 testClass = HdfsSinkIntegrationTests, locations = '{}', classes = '{class org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkIntegrationTests$HdfsSinkApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{server.port:0, spring.hadoop.fsUri=file:///, hdfs.directory=${java.io.tmpdir}/hdfs-sink, org.springframework.boot.test.WebIntegrationTest=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@149e0f5d, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@17046283], resourceBasePath = '', contextLoader = 'org.springframework.boot.test.SpringApplicationContextLoader', parent = [null]]] is not active. Ensure that the context has not been closed programmatically.
	at org.springframework.util.Assert.state(Assert.java:392)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:87)
	at org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener.afterTestMethod(MockRestServiceServerResetTestExecutionListener.java:35)
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:319)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkPropertiesTests
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.371 sec

Results :

Tests in error: 
  testWritingSomething(org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkConfigurationTests): The ApplicationContext loaded for [[WebMergedContextConfiguration@1eeb5818 testClass = HdfsSinkConfigurationTests, locations = '{}', classes = '{class org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkConfigurationTests$HdfsSinkApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{server.port:0, spring.hadoop.fsUri=file:///, hdfs.directory=${java.io.tmpdir}/hdfs-sink, hdfs.closeTimeout=100, org.springframework.boot.test.WebIntegrationTest=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@149e0f5d, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@17046283], resourceBasePath = '', contextLoader = 'org.springframework.boot.test.SpringApplicationContextLoader', parent = [null]]] is not active. Ensure that the context has not been closed programmatically.
  testWritingSomething(org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkIntegrationTests): The ApplicationContext loaded for [[WebMergedContextConfiguration@4348fa35 testClass = HdfsSinkIntegrationTests, locations = '{}', classes = '{class org.springframework.cloud.stream.app.hdfs.sink.HdfsSinkIntegrationTests$HdfsSinkApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{server.port:0, spring.hadoop.fsUri=file:///, hdfs.directory=${java.io.tmpdir}/hdfs-sink, org.springframework.boot.test.WebIntegrationTest=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@149e0f5d, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@17046283], resourceBasePath = '', contextLoader = 'org.springframework.boot.test.SpringApplicationContextLoader', parent = [null]]] is not active. Ensure that the context has not been closed programmatically.

Tests run: 18, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by sobychacko** [comment]
Dependencies for spring-cloud-starter-stream-sink-hdfs after the parent upgrade:

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ spring-cloud-starter-stream-sink-hdfs ---
[INFO] org.springframework.cloud.stream.app:spring-cloud-starter-stream-sink-hdfs:jar:1.1.2.BUILD-SNAPSHOT
[INFO] +- org.springframework.data:spring-data-hadoop-boot:jar:2.4.0.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.4.1.RELEASE:compile
[INFO] |  |  \- org.springframework.boot:spring-boot:jar:1.4.1.RELEASE:compile
[INFO] |  +- org.apache.hadoop:hadoop-yarn-common:jar:2.7.1:compile
[INFO] |  |  +- org.apache.hadoop:hadoop-yarn-api:jar:2.7.1:compile
[INFO] |  |  +- javax.xml.bind:jaxb-api:jar:2.2.2:compile
[INFO] |  |  |  +- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  |  |  \- javax.activation:activation:jar:1.1:compile
[INFO] |  |  +- org.apache.commons:commons-compress:jar:1.4.1:compile
[INFO] |  |  |  \- org.tukaani:xz:jar:1.0:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- org.mortbay.jetty:jetty-util:jar:6.1.26:compile
[INFO] |  |  +- com.sun.jersey:jersey-core:jar:1.19.1:compile
[INFO] |  |  |  \- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  |  +- com.sun.jersey:jersey-client:jar:1.19.1:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.13:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-xc:jar:1.9.13:compile
[INFO] |  |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  |  +- org.apache.hadoop:hadoop-annotations:jar:2.7.1:compile
[INFO] |  |  |  \- jdk.tools:jdk.tools:jar:1.8:system
[INFO] |  |  +- com.google.inject.extensions:guice-servlet:jar:3.0:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:2.5.0:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  |  +- com.google.inject:guice:jar:3.0:compile
[INFO] |  |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  +- com.sun.jersey:jersey-server:jar:1.19.1:compile
[INFO] |  |  +- com.sun.jersey:jersey-json:jar:1.9:compile
[INFO] |  |  |  +- org.codehaus.jettison:jettison:jar:1.1:compile
[INFO] |  |  |  \- com.sun.xml.bind:jaxb-impl:jar:2.2.3-1:compile
[INFO] |  |  \- com.sun.jersey.contribs:jersey-guice:jar:1.9:compile
[INFO] |  +- org.apache.hadoop:hadoop-hdfs:jar:2.7.1:compile
[INFO] |  |  +- commons-daemon:commons-daemon:jar:1.0.13:compile
[INFO] |  |  +- xmlenc:xmlenc:jar:0.52:compile
[INFO] |  |  +- io.netty:netty-all:jar:4.0.23.Final:compile
[INFO] |  |  +- xerces:xercesImpl:jar:2.9.1:compile
[INFO] |  |  |  \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  |  +- org.apache.htrace:htrace-core:jar:3.1.0-incubating:compile
[INFO] |  |  \- org.fusesource.leveldbjni:leveldbjni-all:jar:1.8:compile
[INFO] |  +- org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.7.1:compile
[INFO] |  |  +- org.apache.avro:avro:jar:1.7.4:compile
[INFO] |  |  |  +- com.thoughtworks.paranamer:paranamer:jar:2.3:compile
[INFO] |  |  |  \- org.xerial.snappy:snappy-java:jar:1.1.2:compile
[INFO] |  |  \- io.netty:netty:jar:3.6.2.Final:compile
[INFO] |  +- org.apache.hadoop:hadoop-common:jar:2.7.1:compile
[INFO] |  |  +- org.apache.commons:commons-math3:jar:3.1.1:compile
[INFO] |  |  +- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO] |  |  +- commons-net:commons-net:jar:3.1:compile
[INFO] |  |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  |  +- net.java.dev.jets3t:jets3t:jar:0.9.0:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpclient:jar:4.5:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.1:compile
[INFO] |  |  |  \- com.jamesmurty.utils:java-xmlbuilder:jar:0.4:compile
[INFO] |  |  +- commons-configuration:commons-configuration:jar:1.8:compile
[INFO] |  |  +- com.google.code.gson:gson:jar:2.3.1:compile
[INFO] |  |  +- org.apache.hadoop:hadoop-auth:jar:2.7.1:compile
[INFO] |  |  |  +- org.apache.directory.server:apacheds-kerberos-codec:jar:2.0.0-M15:compile
[INFO] |  |  |  |  +- org.apache.directory.server:apacheds-i18n:jar:2.0.0-M15:compile
[INFO] |  |  |  |  +- org.apache.directory.api:api-asn1-api:jar:1.0.0-M20:compile
[INFO] |  |  |  |  \- org.apache.directory.api:api-util:jar:1.0.0-M20:compile
[INFO] |  |  |  \- org.apache.curator:curator-framework:jar:2.10.0:compile
[INFO] |  |  +- com.jcraft:jsch:jar:0.1.42:compile
[INFO] |  |  +- org.apache.curator:curator-client:jar:2.7.1:compile
[INFO] |  |  +- org.apache.curator:curator-recipes:jar:2.10.0:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] |  |  \- org.apache.zookeeper:zookeeper:jar:3.4.6:compile
[INFO] |  +- org.springframework.data:spring-data-hadoop-config:jar:2.4.0.RELEASE:compile
[INFO] |  |  \- org.springframework.data:spring-data-hadoop-core:jar:2.4.0.RELEASE:compile
[INFO] |  +- org.yaml:snakeyaml:jar:1.17:runtime
[INFO] |  +- org.springframework:spring-aop:jar:4.3.3.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:4.3.3.RELEASE:compile
[INFO] |  +- org.springframework:spring-context-support:jar:4.3.3.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:4.3.3.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:4.3.3.RELEASE:compile
[INFO] |  +- org.apache.hadoop:hadoop-streaming:jar:2.7.1:compile
[INFO] |  +- org.apache.hadoop:hadoop-distcp:jar:2.7.1:compile
[INFO] |  \- org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:2.7.1:compile
[INFO] |     +- org.apache.hadoop:hadoop-mapreduce-client-common:jar:2.7.1:compile
[INFO] |     |  +- org.apache.hadoop:hadoop-yarn-client:jar:2.7.1:compile
[INFO] |     |  \- org.apache.hadoop:hadoop-yarn-server-common:jar:2.7.1:compile
[INFO] |     \- org.apache.hadoop:hadoop-mapreduce-client-shuffle:jar:2.7.1:compile
[INFO] |        \- org.apache.hadoop:hadoop-yarn-server-nodemanager:jar:2.7.1:compile
[INFO] +- org.springframework.data:spring-data-hadoop-store:jar:2.4.0.RELEASE:compile
[INFO] |  +- org.springframework:spring-messaging:jar:4.3.3.RELEASE:compile
[INFO] |  \- org.kitesdk:kite-data-core:jar:1.0.0:compile
[INFO] |     +- org.kitesdk:kite-hadoop-compatibility:jar:1.0.0:compile
[INFO] |     +- com.twitter:parquet-avro:jar:1.4.1:compile
[INFO] |     |  +- com.twitter:parquet-column:jar:1.4.1:compile
[INFO] |     |  |  +- com.twitter:parquet-common:jar:1.4.1:compile
[INFO] |     |  |  \- com.twitter:parquet-encoding:jar:1.4.1:compile
[INFO] |     |  |     \- com.twitter:parquet-generator:jar:1.4.1:compile
[INFO] |     |  +- com.twitter:parquet-hadoop:jar:1.4.1:compile
[INFO] |     |  |  \- com.twitter:parquet-jackson:jar:1.4.1:compile
[INFO] |     |  \- com.twitter:parquet-format:jar:2.0.0:compile
[INFO] |     +- net.sf.opencsv:opencsv:jar:2.3:compile
[INFO] |     +- org.apache.commons:commons-jexl:jar:2.1.1:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-databind:jar:2.8.3:compile
[INFO] |        +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.3:compile
[INFO] |        \- com.fasterxml.jackson.core:jackson-core:jar:2.8.3:compile
[INFO] +- org.springframework.cloud:spring-cloud-stream:jar:1.1.0.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-actuator:jar:1.4.1.RELEASE:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:1.4.1.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-web:jar:1.4.1.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.4.1.RELEASE:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.5:compile
[INFO] |  |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.5:compile
[INFO] |  |  +- org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO] |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |  |  \- com.fasterxml:classmate:jar:1.3.1:compile
[INFO] |  |  +- org.springframework:spring-web:jar:4.3.3.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-webmvc:jar:4.3.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-validation:jar:1.4.1.RELEASE:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.5:compile
[INFO] |  +- org.springframework.integration:spring-integration-core:jar:4.3.4.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-tx:jar:4.3.3.RELEASE:compile
[INFO] |  +- org.springframework.integration:spring-integration-jmx:jar:4.3.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-tuple:jar:1.0.0.RELEASE:compile
[INFO] |  |  \- com.esotericsoftware:kryo-shaded:jar:3.0.3:compile
[INFO] |  |     \- com.esotericsoftware:minlog:jar:1.3.0:compile
[INFO] |  +- org.springframework.integration:spring-integration-tuple:jar:1.0.0.RELEASE:compile
[INFO] |  \- org.springframework.retry:spring-retry:jar:1.1.4.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-configuration-processor:jar:1.4.1.RELEASE:compile
[INFO] |  +- org.json:json:jar:20140107:compile
[INFO] |  \- org.springframework:spring-core:jar:4.3.3.RELEASE:compile
[INFO] +- com.jayway.jsonpath:json-path:jar:2.2.0:compile
[INFO] |  +- net.minidev:json-smart:jar:2.2.1:compile
[INFO] |  |  \- net.minidev:accessors-smart:jar:1.1:compile
[INFO] |  |     \- org.ow2.asm:asm:jar:5.0.3:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO] +- org.springframework.integration:spring-integration-xml:jar:4.3.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-oxm:jar:4.3.3.RELEASE:compile
[INFO] |  \- org.springframework.ws:spring-xml:jar:2.3.0.RELEASE:compile
[INFO] +- org.springframework.cloud:spring-cloud-stream-test-support:jar:1.1.0.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot-starter-test:jar:1.4.1.RELEASE:compile
[INFO] |     +- org.springframework.boot:spring-boot-test:jar:1.4.1.RELEASE:compile
[INFO] |     +- org.springframework.boot:spring-boot-test-autoconfigure:jar:1.4.1.RELEASE:compile
[INFO] |     +- org.assertj:assertj-core:jar:2.5.0:compile
[INFO] |     +- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |     +- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO] |     \- org.skyscreamer:jsonassert:jar:1.2.3:compile
[INFO] +- org.springframework.cloud:spring-cloud-stream-test-support-internal:jar:1.1.0.RELEASE:test
[INFO] |  \- junit:junit:jar:4.12:compile
[INFO] +- org.springframework.integration:spring-integration-test:jar:4.3.4.RELEASE:test
[INFO] |  +- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] |  +- org.mockito:mockito-core:jar:1.10.19:compile
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:compile
[INFO] |  \- org.springframework:spring-test:jar:4.3.3.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-logging:jar:1.4.1.RELEASE:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.1.7:compile
[INFO] |  |  \- ch.qos.logback:logback-core:jar:1.1.7:compile
[INFO] |  +- org.slf4j:jcl-over-slf4j:jar:1.7.21:compile
[INFO] |  +- org.slf4j:jul-to-slf4j:jar:1.7.21:compile
[INFO] |  \- org.slf4j:log4j-over-slf4j:jar:1.7.21:compile
[INFO] \- org.springframework.boot:spring-boot-starter-security:jar:1.4.1.RELEASE:compile
[INFO]    +- org.springframework.boot:spring-boot-starter:jar:1.4.1.RELEASE:compile
[INFO]    +- org.springframework.security:spring-security-config:jar:4.1.3.RELEASE:compile
[INFO]    |  \- org.springframework.security:spring-security-core:jar:4.1.3.RELEASE:compile
[INFO]    \- org.springframework.security:spring-security-web:jar:4.1.3.RELEASE:compile
```

**Comment by JLauzonG** [comment]
Hey, do you remember what was the problem? i'm facing the same issue
